# Build stage
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json npm.lock ./
RUN npm install --frozen-lockfile

# Copy source code
COPY . .

# Build the application
RUN npm build

# Production stage
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install production dependencies only
COPY package.json npm.lock ./
RUN npm install --production --frozen-lockfile

# Copy built assets from builder stage
COPY --from=builder /app/public ./public
COPY --from=builder /app/pgconig.js
COPY --from=builder /app/package.json ./

# Set environment variables
ENV NODE_ENV=production

# Expose port 3000
EXPOSE ${PORT:9016}

# Start the production server
CMD ["npm", "start"] 